baseURL = "https://alexherbo2.github.io"
languageCode = "en-us"
title = "alexherbo2"
theme = "steve-losh"

buildDrafts = true
enableGitInfo = true

[params]
  # https://golang.org/pkg/time#pkg-constants
  dateForm = "January 2, 2006"
  icon = "https://github.com/favicon.ico"
  js = [
    "packages/modal.js",
    "packages/mouse-selection.js",
    "packages/prompt.js",
    "packages/hint.js",
    "packages/mark.js",
    "packages/selection.js",
    "packages/mouse.js",
    "packages/clipboard.js",
    "packages/scroll.js",
    "packages/player.js",
    "packages/krabby.js",
    "config.js"
  ]
  css = [
    "packages/selection.css",
    "packages/krabby.css"
  ]

[params.pages]
  raw = "https://github.com/alexherbo2/website/raw/master/content/%s"
  history = "https://github.com/alexherbo2/website/commits/master/content/%s"
  edit = "https://github.com/alexherbo2/website/edit/master/content/%s"

[params.host]
  name = "GitHub"
  repository = "https://github.com/alexherbo2/website"

[menu]

  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/alexherbo2"

  [[menu.social]]
    name = "YouTube"
    url = "https://youtube.com/channel/UCv9nzkds34PnGOu6u_QvVBQ"

  [[menu.social]]
    name = "Instagram"
    url = "https://instagram.com/alexherbo2"

  [[menu.navigation]]
    name = "Blog"
    url = "/blog"

  [[menu.navigation]]
    name = "Projects"
    url = "/projects"

  [[menu.navigation]]
    name = "Config"
    url = "/config"

  [[menu.navigation]]
    name = "Citations"
    url = "/citations"

  [[menu.navigation]]
    name = "Wiki"
    url = "/wiki"
