#!/bin/sh

fetch() {
  case $# in
    1) curl --location --remote-name $1 ;;
    2) curl --location $1 --output $2 ;;
  esac
}

mkdir -p static/packages
cd static/packages

fetch https://github.com/alexherbo2/krabby/raw/master/website/krabby.js
fetch https://github.com/alexherbo2/krabby/raw/master/src/krabby.css
fetch https://github.com/alexherbo2/krabby/raw/master/scripts/fetch - | sh
